version: '3'
services:
  postgres:
    image: postgres:16.3
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: fullstack
      POSTGRES_PASSWORD: fullstack
      POSTGRES_DB: fullstrack
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
